import { FreeeApiError, type PublicFreeeClient } from "../../lib/clients/freee-public-client.js";
import { redact } from "../../lib/audit/redactor.js";
import type { QuotationAuditEntry } from "../../lib/audit/quotation-audit.js";
import { computeInvoiceTotals } from "../../domain/invoice-plan.js";
import { parseQuotationPlan } from "../../domain/quotation-plan.js";
export type QuotationPostState = "not_attempted" | "rejected" | "unknown" | "succeeded";
export interface QuotationCreateOptions { companyId: number; planPath: string; execute: boolean; logDir: string; taskId: string; }
export interface QuotationCreateDeps { getClient: () => Promise<PublicFreeeClient>; readFile: (path: string) => Promise<string>; appendAudit: (entry: QuotationAuditEntry) => Promise<void>; now: () => Date; }
export interface QuotationCreateResult { mode: "dry-run" | "execute"; payload: Record<string, unknown>; totals: { subtotal: number; tax: number; total: number }; created?: { id: number; quotation_number: string; total_amount: number; report_url: string }; }
function warning(state: QuotationPostState, id?: number) { const which = id === undefined ? "id 不明" : `id=${id}`; if (state === "succeeded") return `見積書は作成済みの可能性がある（POST は 2xx・${which}）。再実行せず freee Web で確認すること`; if (state === "unknown") return "POST の結果が不明（送信後の通信失敗または 5xx 応答）。サーバー側で作成済みかもしれないため、再実行せず freee Web で確認すること"; return state === "rejected" ? "POST は 4xx で拒否された（再実行可）" : "POST は行っていない（再実行可）"; }
export class QuotationCreatedButUnverifiedError extends Error { constructor(readonly createdId: number | undefined, readonly reason: string, readonly postState: Extract<QuotationPostState, "unknown" | "succeeded">) { super(`quotation create: ${warning(postState, createdId)}（${reason}）`); this.name = "QuotationCreatedButUnverifiedError"; } }
export class QuotationCreateAuditWriteError extends Error { constructor(readonly status: string, readonly createdId: number | undefined, readonly postState: QuotationPostState, detail: string) { super(`quotation create: audit（${status}）の書き込みに失敗（${detail}）。${warning(postState, createdId)}`); this.name = "QuotationCreateAuditWriteError"; } }
class ResponseParseError extends Error { constructor(readonly path: string) { super(`invalid response: ${path}`); } }
async function audit(deps: QuotationCreateDeps, entry: QuotationAuditEntry, state: QuotationPostState) { try { await deps.appendAudit(entry); } catch (e) { throw new QuotationCreateAuditWriteError(entry.status, entry.created_id, state, e instanceof Error ? e.message : String(e)); } }
function failure(e: unknown) { if (e instanceof FreeeApiError) return `api_error:${e.status}:${e.path}`; if (e instanceof ResponseParseError) return `invalid_response:${e.path}`; return "request_failed:/quotations"; }
export async function runQuotationsCreate(opts: QuotationCreateOptions, deps: QuotationCreateDeps): Promise<QuotationCreateResult> { const plan = parseQuotationPlan(JSON.parse(await deps.readFile(opts.planPath))), payload = { company_id: opts.companyId, ...plan }, mode = opts.execute ? "execute" as const : "dry-run" as const, totals = computeInvoiceTotals(plan), base = { task_id: opts.taskId, event: "quotation_create" as const, mode, company_id: opts.companyId, payload_redacted: redact(payload) }; if (!opts.execute) { await audit(deps, { ...base, timestamp: deps.now().toISOString(), status: "planned" }, "not_attempted"); return { mode, payload, totals }; } let state: QuotationPostState = "not_attempted", createdId: number | undefined; try { const client = await deps.getClient(); let post: Response; try { state = "unknown"; post = await client.post("/quotations", { body: payload }); state = "succeeded"; } catch (e) { if (e instanceof FreeeApiError && e.status < 500) state = "rejected"; throw e; } let p: { quotation?: { id?: unknown } }; try { p = await post.json() as { quotation?: { id?: unknown } }; } catch { throw new ResponseParseError("/quotations"); } if (!Number.isSafeInteger(p.quotation?.id) || (p.quotation?.id as number) < 1) throw new ResponseParseError("/quotations"); createdId = p.quotation!.id as number; const get = await client.get(`/quotations/${createdId}`, { query: { company_id: opts.companyId } }); let detail: { quotation?: Record<string, unknown> }; try { detail = await get.json() as { quotation?: Record<string, unknown> }; } catch { throw new ResponseParseError("/quotations/{id}"); } const q = detail.quotation; if (!q || q.id !== createdId || typeof q.quotation_number !== "string" || typeof q.total_amount !== "number" || typeof q.report_url !== "string") throw new ResponseParseError("/quotations/{id}"); await audit(deps, { ...base, timestamp: deps.now().toISOString(), status: "created", created_id: createdId, post_state: state }, state); return { mode, payload, totals, created: { id: createdId, quotation_number: q.quotation_number, total_amount: q.total_amount, report_url: q.report_url } }; } catch (e) { if (e instanceof QuotationCreateAuditWriteError) throw e; const why = failure(e), entry: QuotationAuditEntry = { ...base, timestamp: deps.now().toISOString(), status: "failed", reason: why, post_state: state }; if (createdId !== undefined) entry.created_id = createdId; await audit(deps, entry, state); if ((state as QuotationPostState) === "unknown" || (state as QuotationPostState) === "succeeded") throw new QuotationCreatedButUnverifiedError(createdId, why, state as Extract<QuotationPostState, "unknown" | "succeeded">); throw e; } }
export function formatQuotationCreate(result: QuotationCreateResult): string { const out = [`mode: ${result.mode}`, `参考値（確定値は freee の応答を正とする）: 小計 ${result.totals.subtotal} / 消費税 ${result.totals.tax} / 合計 ${result.totals.total}`]; if (result.created) out.push(`created: id=${result.created.id} quotation_number=${result.created.quotation_number} total_amount=${result.created.total_amount}`, `report_url: ${result.created.report_url}`); else out.push("実 POST は行っていません（--execute で作成）", "見積書番号の採番設定は API から読めないため、quotation_number の要否は検証していません"); out.push("payload:", JSON.stringify(result.payload, null, 2)); return out.join("\n"); }
