import type { PublicFreeeClient } from "../../lib/clients/freee-public-client.js";
import { toQuotationSummary, type QuotationSummary } from "../../types/quotation.js";
export interface QuotationsListOptions { companyId: number; quotationNumber?: string; subject?: string; partnerIds?: string; sendingStatus?: "sent" | "unsent"; cancelStatus?: "canceled" | "uncanceled"; startQuotationDate?: string; endQuotationDate?: string; startExpirationDate?: string; endExpirationDate?: string; salesManagementOrigin?: boolean; maxOffset?: number; }
export interface QuotationsListDeps { client: PublicFreeeClient; }
export interface QuotationsListResult { items: QuotationSummary[]; }
const DATE = /^\d{4}-\d{2}-\d{2}$/; export const QUOTATION_PAGINATION_MAX_OFFSET = 10_000;
export function validateQuotationsListOptions(opts: QuotationsListOptions): void { for (const [key, value] of Object.entries({ "start-quotation-date": opts.startQuotationDate, "end-quotation-date": opts.endQuotationDate, "start-expiration-date": opts.startExpirationDate, "end-expiration-date": opts.endExpirationDate })) if (value !== undefined && !DATE.test(value)) throw new Error(`--${key} must be YYYY-MM-DD`); if (opts.partnerIds !== undefined && (opts.partnerIds.split(",").length > 3 || opts.partnerIds.split(",").some((id) => !/^[1-9]\d*$/.test(id)))) throw new Error("--partner-ids must be one to three comma-separated positive integer IDs"); }
export async function runQuotationsList(opts: QuotationsListOptions, deps: QuotationsListDeps): Promise<QuotationsListResult> { validateQuotationsListOptions(opts); const limit = 100, max = opts.maxOffset ?? QUOTATION_PAGINATION_MAX_OFFSET, items: QuotationSummary[] = []; const query = { company_id: opts.companyId, quotation_number: opts.quotationNumber, subject: opts.subject, partner_ids: opts.partnerIds, sending_status: opts.sendingStatus, cancel_status: opts.cancelStatus, start_quotation_date: opts.startQuotationDate, end_quotation_date: opts.endQuotationDate, start_expiration_date: opts.startExpirationDate, end_expiration_date: opts.endExpirationDate, sales_management_origin: opts.salesManagementOrigin || undefined }; let offset = 0; while (true) { if (offset + limit > max) throw new Error(`quotations list: limit + offset が ${max} を超えるため中断しました`); const response = await deps.client.get("/quotations", { query: { ...query, limit, offset } }); const payload = await response.json() as { quotations?: unknown }; if (!Array.isArray(payload.quotations)) throw new Error("quotations list: response is missing quotations"); const page = payload.quotations as Array<Record<string, unknown>>; items.push(...page.map(toQuotationSummary)); if (page.length < limit) return { items }; offset += page.length; } }
export function formatQuotationsList(result: QuotationsListResult, format: "json" | "table"): string { if (format === "json") return JSON.stringify(result.items, null, 2); return ["id\tquotation_number\tquotation_date\tpartner_name\ttotal_amount\tsending_status\tcancel_status\treport_url", ...result.items.map((item) => [item.id, item.quotation_number, item.quotation_date, item.partner_name ?? "", item.total_amount, item.sending_status, item.cancel_status, item.report_url].join("\t"))].join("\n"); }
