import { FreeeApiError, type PublicFreeeClient } from "../../lib/clients/freee-public-client.js";
import type { QuotationUncancelAuditEntry } from "../../lib/audit/quotation-audit.js";
import { validateQuotationId } from "./id.js";

export type QuotationUncancelPutState = "not_attempted" | "rejected" | "unknown" | "succeeded";
type Phase = "initial_get" | "put";
export interface QuotationUncancelOptions { companyId: number; id: number; execute: boolean; logDir: string; taskId: string; expectQuotationNumber?: string; }
export interface QuotationUncancelDeps { getClient: () => Promise<PublicFreeeClient>; appendAudit: (entry: QuotationUncancelAuditEntry) => Promise<void>; now: () => Date; }
export interface QuotationUncancelResult { mode: "dry-run" | "execute"; companyId: number; id: number; target: { quotation_number: string; total_amount: number; partner_id: number }; uncanceled?: { id: number; cancel_status: "uncanceled" }; }
export class QuotationUncancelResponseParseError extends Error { constructor(readonly path: string) { super(`invalid response: ${path}`); this.name = "QuotationUncancelResponseParseError"; } }
export class QuotationUncancelGuardError extends Error { constructor(readonly reason: string) { super(`quotation uncancel: guard rejected (${reason})`); this.name = "QuotationUncancelGuardError"; } }
export class QuotationUncancelAuditWriteError extends Error { constructor(readonly detail: string) { super(`quotation uncancel: audit write failed (${detail})`); this.name = "QuotationUncancelAuditWriteError"; } }
export class QuotationUncancelUnverifiedError extends Error { constructor(readonly reason: string, readonly putState: Extract<QuotationUncancelPutState, "unknown" | "succeeded">) { super(`quotation uncancel: ${putState === "succeeded" ? "復元済みの可能性がある" : "PUT の結果が不明"}ため、再実行せず freee Web で確認すること（${reason}）`); this.name = "QuotationUncancelUnverifiedError"; } }
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);
const positiveInteger = (value: unknown): value is number => typeof value === "number" && Number.isSafeInteger(value) && value > 0;
const pathFor = (id: number) => `/quotations/${id}`;
async function parseJson(response: Response, path: string): Promise<unknown> { try { return await response.json(); } catch { throw new QuotationUncancelResponseParseError(path); } }
function readTarget(payload: unknown, id: number, companyId: number): { target: QuotationUncancelResult["target"]; cancelStatus: unknown } { const quotation = isRecord(payload) && isRecord(payload.quotation) ? payload.quotation : undefined; const path = pathFor(id); if (!quotation || !positiveInteger(quotation.id) || !positiveInteger(quotation.company_id) || typeof quotation.quotation_number !== "string" || typeof quotation.total_amount !== "number" || !positiveInteger(quotation.partner_id)) throw new QuotationUncancelResponseParseError(path); if (quotation.id !== id) throw new QuotationUncancelGuardError("mismatch:id"); if (quotation.company_id !== companyId) throw new QuotationUncancelGuardError("mismatch:company_id"); return { target: { quotation_number: quotation.quotation_number, total_amount: quotation.total_amount, partner_id: quotation.partner_id }, cancelStatus: quotation.cancel_status }; }
function assertCanceledStatus(cancelStatus: unknown, path: string): void { if (cancelStatus !== "canceled" && cancelStatus !== "uncanceled") throw new QuotationUncancelResponseParseError(path); if (cancelStatus === "uncanceled") throw new QuotationUncancelGuardError("not_canceled"); }
function readUncanceled(payload: unknown, id: number): { id: number; cancel_status: "uncanceled" } { const path = `${pathFor(id)}/uncancel`; const quotation = isRecord(payload) && isRecord(payload.quotation) ? payload.quotation : undefined; if (!quotation || !positiveInteger(quotation.id)) throw new QuotationUncancelResponseParseError(path); if (quotation.id !== id) throw new QuotationUncancelGuardError("mismatch:id"); if (quotation.cancel_status !== "uncanceled") throw new QuotationUncancelGuardError("mismatch:cancel_status"); return { id: quotation.id, cancel_status: "uncanceled" }; }
async function appendAudit(deps: QuotationUncancelDeps, entry: QuotationUncancelAuditEntry): Promise<void> { try { await deps.appendAudit(entry); } catch (error) { throw new QuotationUncancelAuditWriteError(error instanceof Error ? error.message : String(error)); } }
function reason(error: unknown, phase: Phase): string { if (error instanceof QuotationUncancelGuardError) return error.reason; if (error instanceof QuotationUncancelAuditWriteError) return "audit_write_failed"; if (error instanceof QuotationUncancelResponseParseError) return `invalid_response:${error.path}`; if (error instanceof FreeeApiError) return `${phase}_http:${error.status}`; return `${phase}_network`; }
function classifyPutState(error: unknown): QuotationUncancelPutState { return error instanceof FreeeApiError && [400, 401, 403, 404].includes(error.status) ? "rejected" : "unknown"; }
function canExposeAuditError(state: QuotationUncancelPutState): boolean { return state === "not_attempted" || state === "rejected"; }
function mustWrapUnverified(state: QuotationUncancelPutState): state is "unknown" | "succeeded" { return state === "unknown" || state === "succeeded"; }
export async function runQuotationsUncancel(opts: QuotationUncancelOptions, deps: QuotationUncancelDeps): Promise<QuotationUncancelResult> {
  validateQuotationId(opts.id); const mode = opts.execute ? "execute" as const : "dry-run" as const; const base = { task_id: opts.taskId, event: "quotation_uncancel" as const, mode, company_id: opts.companyId, quotation_id: opts.id }; let putState: QuotationUncancelPutState = "not_attempted"; let phase: Phase = "initial_get"; let clientFailureAudited = false;
  try { if (opts.execute && opts.expectQuotationNumber === undefined) throw new QuotationUncancelGuardError("mismatch:quotation_number"); let client: PublicFreeeClient; try { client = await deps.getClient(); } catch (error) { await appendAudit(deps, { ...base, timestamp: deps.now().toISOString(), status: "failed", reason: "client_unavailable", put_state: putState }); clientFailureAudited = true; throw error; }
    const { target, cancelStatus } = readTarget(await parseJson(await client.get(pathFor(opts.id), { query: { company_id: opts.companyId } }), pathFor(opts.id)), opts.id, opts.companyId); if (opts.expectQuotationNumber !== undefined && target.quotation_number !== opts.expectQuotationNumber) throw new QuotationUncancelGuardError("mismatch:quotation_number"); assertCanceledStatus(cancelStatus, pathFor(opts.id)); if (!opts.execute) { await appendAudit(deps, { ...base, timestamp: deps.now().toISOString(), status: "planned", put_state: putState }); return { mode, companyId: opts.companyId, id: opts.id, target }; }
    phase = "put"; let response: Response; try { putState = "unknown"; response = await client.put(`${pathFor(opts.id)}/uncancel`, { body: { company_id: opts.companyId }, redirect: "manual" }); putState = "succeeded"; } catch (error) { putState = classifyPutState(error); throw error; } const uncanceled = readUncanceled(await parseJson(response, `${pathFor(opts.id)}/uncancel`), opts.id); await appendAudit(deps, { ...base, timestamp: deps.now().toISOString(), status: "uncanceled", put_state: putState }); return { mode, companyId: opts.companyId, id: opts.id, target, uncanceled };
  } catch (error) { const failureReason = reason(error, phase); let auditFailure = error instanceof QuotationUncancelAuditWriteError; if (!auditFailure && !clientFailureAudited) { try { await appendAudit(deps, { ...base, timestamp: deps.now().toISOString(), status: "failed", reason: failureReason, put_state: putState }); } catch (auditError) { auditFailure = true; if (canExposeAuditError(putState)) throw auditError; } } if (mustWrapUnverified(putState)) throw new QuotationUncancelUnverifiedError(auditFailure ? "audit_write_failed" : failureReason, putState); throw error; }
}
export function formatQuotationUncancel(result: QuotationUncancelResult): string { return [`mode: ${result.mode}`, `target: quotation_number=${result.target.quotation_number} total_amount=${result.target.total_amount} partner_id=${result.target.partner_id}`, result.uncanceled ? `uncanceled: id=${result.uncanceled.id} cancel_status=uncanceled（復元後の番号は確認していません）` : "実 PUT は行っていません（--execute で復元）"].join("\n"); }
