import { FreeeApiError, type PublicFreeeClient } from "../../lib/clients/freee-public-client.js";
import type { InvoiceUncancelAuditEntry } from "../../lib/audit/invoice-audit.js";
import { validateInvoiceMutationId } from "./id.js";

export type InvoiceUncancelPutState = "not_attempted" | "rejected" | "unknown" | "succeeded";
type Phase = "initial_get" | "put";
export interface InvoiceUncancelOptions { companyId: number; id: number; execute: boolean; logDir: string; taskId: string; expectInvoiceNumber?: string; }
export interface InvoiceUncancelDeps { getClient: () => Promise<PublicFreeeClient>; appendAudit: (entry: InvoiceUncancelAuditEntry) => Promise<void>; now: () => Date; }
export interface InvoiceUncancelResult { mode: "dry-run" | "execute"; companyId: number; id: number; target: { invoice_number: string; total_amount: number; partner_id: number }; uncanceled?: { id: number; cancel_status: "uncanceled" }; }
export class InvoiceUncancelResponseParseError extends Error { constructor(readonly path: string) { super(`invalid response: ${path}`); this.name = "InvoiceUncancelResponseParseError"; } }
export class InvoiceUncancelGuardError extends Error { constructor(readonly reason: string) { super(`invoice uncancel: guard rejected (${reason})`); this.name = "InvoiceUncancelGuardError"; } }
export class InvoiceUncancelAuditWriteError extends Error { constructor(readonly detail: string) { super(`invoice uncancel: audit write failed (${detail})`); this.name = "InvoiceUncancelAuditWriteError"; } }
export class InvoiceUncancelUnverifiedError extends Error { constructor(readonly reason: string, readonly putState: Extract<InvoiceUncancelPutState, "unknown" | "succeeded">) { super(`invoice uncancel: ${putState === "succeeded" ? "復元済みの可能性がある" : "PUT の結果が不明"}ため、再実行せず freee Web で確認すること（${reason}）`); this.name = "InvoiceUncancelUnverifiedError"; } }
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);
const positiveInteger = (value: unknown): value is number => typeof value === "number" && Number.isSafeInteger(value) && value > 0;
const pathFor = (id: number) => `/invoices/${id}`;
async function parseJson(response: Response, path: string): Promise<unknown> { try { return await response.json(); } catch { throw new InvoiceUncancelResponseParseError(path); } }
function readTarget(payload: unknown, id: number, companyId: number): { target: InvoiceUncancelResult["target"]; cancelStatus: unknown } { const invoice = isRecord(payload) && isRecord(payload.invoice) ? payload.invoice : undefined; const path = pathFor(id); if (!invoice || !positiveInteger(invoice.id) || !positiveInteger(invoice.company_id) || typeof invoice.invoice_number !== "string" || typeof invoice.total_amount !== "number" || !positiveInteger(invoice.partner_id)) throw new InvoiceUncancelResponseParseError(path); if (invoice.id !== id) throw new InvoiceUncancelGuardError("mismatch:id"); if (invoice.company_id !== companyId) throw new InvoiceUncancelGuardError("mismatch:company_id"); return { target: { invoice_number: invoice.invoice_number, total_amount: invoice.total_amount, partner_id: invoice.partner_id }, cancelStatus: invoice.cancel_status }; }
function assertCanceledStatus(cancelStatus: unknown, path: string): void { if (cancelStatus !== "canceled" && cancelStatus !== "uncanceled") throw new InvoiceUncancelResponseParseError(path); if (cancelStatus === "uncanceled") throw new InvoiceUncancelGuardError("not_canceled"); }
function readUncanceled(payload: unknown, id: number): { id: number; cancel_status: "uncanceled" } { const path = `${pathFor(id)}/uncancel`; const invoice = isRecord(payload) && isRecord(payload.invoice) ? payload.invoice : undefined; if (!invoice || !positiveInteger(invoice.id)) throw new InvoiceUncancelResponseParseError(path); if (invoice.id !== id) throw new InvoiceUncancelGuardError("mismatch:id"); if (invoice.cancel_status !== "uncanceled") throw new InvoiceUncancelGuardError("mismatch:cancel_status"); return { id: invoice.id, cancel_status: "uncanceled" }; }
async function appendAudit(deps: InvoiceUncancelDeps, entry: InvoiceUncancelAuditEntry): Promise<void> { try { await deps.appendAudit(entry); } catch (error) { throw new InvoiceUncancelAuditWriteError(error instanceof Error ? error.message : String(error)); } }
function reason(error: unknown, phase: Phase): string { if (error instanceof InvoiceUncancelGuardError) return error.reason; if (error instanceof InvoiceUncancelAuditWriteError) return "audit_write_failed"; if (error instanceof InvoiceUncancelResponseParseError) return `invalid_response:${error.path}`; if (error instanceof FreeeApiError) return `${phase}_http:${error.status}`; return `${phase}_network`; }
function classifyPutState(error: unknown): InvoiceUncancelPutState { return error instanceof FreeeApiError && [400, 401, 403, 404].includes(error.status) ? "rejected" : "unknown"; }
function canExposeAuditError(state: InvoiceUncancelPutState): boolean { return state === "not_attempted" || state === "rejected"; }
function mustWrapUnverified(state: InvoiceUncancelPutState): state is "unknown" | "succeeded" { return state === "unknown" || state === "succeeded"; }
export async function runInvoicesUncancel(opts: InvoiceUncancelOptions, deps: InvoiceUncancelDeps): Promise<InvoiceUncancelResult> {
  validateInvoiceMutationId(opts.id); const mode = opts.execute ? "execute" as const : "dry-run" as const; const base = { task_id: opts.taskId, event: "invoice_uncancel" as const, mode, company_id: opts.companyId, invoice_id: opts.id }; let putState: InvoiceUncancelPutState = "not_attempted"; let phase: Phase = "initial_get"; let clientFailureAudited = false;
  try { if (opts.execute && opts.expectInvoiceNumber === undefined) throw new InvoiceUncancelGuardError("mismatch:invoice_number"); let client: PublicFreeeClient; try { client = await deps.getClient(); } catch (error) { await appendAudit(deps, { ...base, timestamp: deps.now().toISOString(), status: "failed", reason: "client_unavailable", put_state: putState }); clientFailureAudited = true; throw error; }
    const { target, cancelStatus } = readTarget(await parseJson(await client.get(pathFor(opts.id), { query: { company_id: opts.companyId } }), pathFor(opts.id)), opts.id, opts.companyId); if (opts.expectInvoiceNumber !== undefined && target.invoice_number !== opts.expectInvoiceNumber) throw new InvoiceUncancelGuardError("mismatch:invoice_number"); assertCanceledStatus(cancelStatus, pathFor(opts.id)); if (!opts.execute) { await appendAudit(deps, { ...base, timestamp: deps.now().toISOString(), status: "planned", put_state: putState }); return { mode, companyId: opts.companyId, id: opts.id, target }; }
    phase = "put"; let response: Response; try { putState = "unknown"; response = await client.put(`${pathFor(opts.id)}/uncancel`, { body: { company_id: opts.companyId }, redirect: "manual" }); putState = "succeeded"; } catch (error) { putState = classifyPutState(error); throw error; } const uncanceled = readUncanceled(await parseJson(response, `${pathFor(opts.id)}/uncancel`), opts.id); await appendAudit(deps, { ...base, timestamp: deps.now().toISOString(), status: "uncanceled", put_state: putState }); return { mode, companyId: opts.companyId, id: opts.id, target, uncanceled };
  } catch (error) { const failureReason = reason(error, phase); let auditFailure = error instanceof InvoiceUncancelAuditWriteError; if (!auditFailure && !clientFailureAudited) { try { await appendAudit(deps, { ...base, timestamp: deps.now().toISOString(), status: "failed", reason: failureReason, put_state: putState }); } catch (auditError) { auditFailure = true; if (canExposeAuditError(putState)) throw auditError; } } if (mustWrapUnverified(putState)) throw new InvoiceUncancelUnverifiedError(auditFailure ? "audit_write_failed" : failureReason, putState); throw error; }
}
export function formatInvoiceUncancel(result: InvoiceUncancelResult): string { return [`mode: ${result.mode}`, `target: invoice_number=${result.target.invoice_number} total_amount=${result.target.total_amount} partner_id=${result.target.partner_id}`, result.uncanceled ? `uncanceled: id=${result.uncanceled.id} cancel_status=uncanceled（復元後の番号は確認していません）` : "実 PUT は行っていません（--execute で復元）"].join("\n"); }
