import type { PublicFreeeClient } from "../../lib/clients/freee-public-client.js";
import { FreeeApiError } from "../../lib/clients/freee-public-client.js";
import { invoiceWebUrl } from "../../lib/clients/freee-invoice-client.js";
import { redact } from "../../lib/audit/redactor.js";
import type { InvoiceUpdateAuditEntry } from "../../lib/audit/invoice-audit.js";
import { computeInvoiceTotals, INVOICE_PLAN_ALLOWED_KEYS, INVOICE_PLAN_ALLOWED_LINE_KEYS, parseInvoicePlanLine, parseInvoiceUpdatePlan, type InvoiceTotals } from "../../domain/invoice-plan.js";
import { classifyInvoicePutState } from "./cancel.js";
import { validateInvoiceMutationId } from "./id.js";

export type InvoiceUpdatePutState = "not_attempted" | "rejected" | "unknown" | "succeeded";
export type { InvoiceUpdateAuditEntry } from "../../lib/audit/invoice-audit.js";
export const RESPONSE_COPY_KEYS = ["company_id", "invoice_number", "branch_no", "subject", "template_id", "billing_date", "issue_date", "payment_date", "payment_type", "invoice_note", "memo", "tax_entry_method", "tax_fraction", "line_amount_fraction", "withholding_tax_entry_method", "amount_brought_forward", "partner_id", "partner_code", "partner_title", "partner_address_zipcode", "partner_address_prefecture_code", "partner_address_street_name1", "partner_address_street_name2", "partner_contact_department", "partner_contact_name", "partner_display_name", "partner_bank_account", "company_contact_name", "company_name", "company_description", "bank_account_to_transfer", "lines"] as const;
export const RESPONSE_DROP_KEYS = ["id", "template_name", "sending_status", "payment_status", "cancel_status", "deal_status", "deal_id", "total_amount", "created_at", "amount_withholding_tax", "amount_including_tax", "amount_excluding_tax", "amount_tax", "amount_including_tax_10", "amount_excluding_tax_10", "amount_tax_10", "amount_including_tax_8", "amount_excluding_tax_8", "amount_tax_8", "amount_including_tax_8_reduced", "amount_excluding_tax_8_reduced", "amount_tax_8_reduced", "amount_including_tax_0", "amount_excluding_tax_0", "amount_tax_0", "partner_name", "template", "email_url_file_downloaded_at", "email_url_file_downloaded_status", "report_url", "sales_management_origin"] as const;
const COPY = new Set<string>(RESPONSE_COPY_KEYS); const DROP = new Set<string>(RESPONSE_DROP_KEYS);
export const RESPONSE_LINE_COPY_KEYS = ["type", "description", "sales_date", "unit", "quantity", "unit_price", "tax_rate", "reduced_tax_rate", "withholding"] as const;
export const RESPONSE_LINE_DROP_KEYS = ["id", "amount_excluding_tax"] as const;
const LINE_COPY = new Set<string>(RESPONSE_LINE_COPY_KEYS);
const LINE_DROP = new Set<string>(RESPONSE_LINE_DROP_KEYS);
const UNOBSERVABLE = { top: ["include_amount_brought_forward", "partner_contact_email_to", "partner_contact_email_cc", "partner_sending_method"], lines: ["account_item_id", "tax_code", "item_id", "section_id", "tag_ids", "segment_1_tag_id", "segment_2_tag_id", "segment_3_tag_id"] };
export const UNOBSERVABLE_WARNING = "警告: GET から復元して送れない12項目があります。plan に明示すれば partner_contact_email_to / partner_contact_email_cc / lines[].tag_ids の3項目は送れますが、残る9項目は allowlist 外です。上位4項目はメール宛先・送付方法・繰越設定、明細8項目は取引登録の下書きに関わります。PUT が置換動作なら、明示しない既存値が失われる可能性があります。";
export const UNOBSERVABLE_DETAIL = `復元して送れない項目 — 上位: ${UNOBSERVABLE.top.join(", ")} / 明細: ${UNOBSERVABLE.lines.join(", ")}`;
const validPartnerId = (v: unknown): boolean => typeof v === "number" && Number.isSafeInteger(v) && v > 0;
const validPartnerCode = (v: unknown): boolean => typeof v === "string" && v.length > 0;
const PAYLOAD_TOP_KEYS = new Set<string>([...RESPONSE_COPY_KEYS, ...INVOICE_PLAN_ALLOWED_KEYS]);
const PAYLOAD_LINE_KEYS = new Set<string>([...RESPONSE_LINE_COPY_KEYS, ...INVOICE_PLAN_ALLOWED_LINE_KEYS]);
/** PUT 応答の明細に現れうるキー。**仕様（OpenAPI の InvoiceResponse_invoice_lines）が管理元**で、fixture と完全一致することをテストで固定する。 */
export const PUT_RESPONSE_LINE_KEYS_LIST = ["account_item_id", "amount_excluding_tax", "description", "id", "item_id", "quantity", "reduced_tax_rate", "sales_date", "section_id", "segment_1_tag_id", "segment_2_tag_id", "segment_3_tag_id", "tag_ids", "tax_code", "tax_rate", "type", "unit", "unit_price", "withholding"] as const;
const PUT_RESPONSE_LINE_KEYS = new Set<string>(PUT_RESPONSE_LINE_KEYS_LIST);
/**
 * GET の空文字を「未指定」として payload から落とすキー。
 * **`minLength >= 1` から導出してはいけない。** `partner_address_*` / `partner_contact_*` も
 * `minLength: 1` だが、**省略すると取引先マスタの値が補完される**（`InvoiceRequest` の
 * description に明記）ため、落とすと無関係な更新で帳票の宛先が変わる。
 * ここに入れるのは「GET で required（＝未設定が `""` で表れる）かつ補完の記述が無い」キーだけ。
 */
const EMPTY_AS_UNSET = new Set(["subject", "memo"]);
const UPDATE_AUDIT_REDACT_KEYS = new Set(["partner_contact_name", "partner_contact_department", "partner_display_name", "partner_address_zipcode", "partner_address_prefecture_code", "partner_address_street_name1", "partner_address_street_name2", "partner_bank_account", "bank_account_to_transfer", "company_contact_name", "partner_contact_email_to", "partner_contact_email_cc"]);
const isRecord = (x: unknown): x is Record<string, unknown> => typeof x === "object" && x !== null && !Array.isArray(x);
const pathFor = (id: number) => `/invoices/${id}`;
export class InvoiceUpdateGuardError extends Error { constructor(readonly reason: string) { super(`invoice update: guard rejected (${reason})`); this.name = "InvoiceUpdateGuardError"; } }
class ResponseParseError extends Error { constructor(readonly path: string) { super(`invoice update: invalid response ${path}`); this.name = "ResponseParseError"; } }
class AuditWriteError extends Error { constructor(readonly detail: string) { super(`invoice update: audit write failed (${detail})`); this.name = "AuditWriteError"; } }
export class InvoiceUpdateUnverifiedError extends Error { constructor(readonly reason: string, readonly putState: Extract<InvoiceUpdatePutState, "unknown" | "succeeded">) { super(`invoice update: ${putState === "succeeded" ? "更新済みの可能性がある" : "PUT の結果が不明"}ため、再実行せず freee Web で確認すること（${reason}）`); this.name = "InvoiceUpdateUnverifiedError"; } }
export interface InvoiceUpdateOptions { companyId: number; id: number; planPath: string; execute: boolean; logDir: string; taskId: string; expectInvoiceNumber?: string; allowDealRegistered: boolean; }
export interface InvoiceUpdateDeps { getClient: () => Promise<PublicFreeeClient>; readFile: (path: string) => Promise<string>; appendAudit: (entry: InvoiceUpdateAuditEntry) => Promise<void>; now: () => Date; }
export interface InvoiceUpdateResult { mode: "dry-run" | "execute"; companyId: number; id: number; target: { invoice_number: string; total_amount: number; cancel_status: string; deal_status: string; sending_status: string }; unobservable: { top: string[]; lines: string[] }; changes: Array<{ path: string; current: unknown; next: unknown; same: boolean }>; totals: InvoiceTotals; payload: Record<string, unknown>; updated?: { id: number; invoice_number: string; total_amount: number; webUrl: string }; }
async function json(response: Response, path: string): Promise<unknown> { try { return await response.json(); } catch { throw new ResponseParseError(path); } }
function copyLine(value: unknown): Record<string, unknown> { if (!isRecord(value)) throw new ResponseParseError("/invoices/{id}"); const out: Record<string, unknown> = {}; for (const [key, item] of Object.entries(value)) { if (!LINE_COPY.has(key) && !LINE_DROP.has(key)) throw new InvoiceUpdateGuardError(`unmapped_response_key:lines[].${key}`); } const keys = value.type === "text" ? ["type", "description"] : RESPONSE_LINE_COPY_KEYS; for (const key of keys) if (value[key] !== null && value[key] !== undefined) out[key] = value[key]; return out; }
function readCurrent(value: unknown, id: number, companyId: number): { current: Record<string, unknown>; target: InvoiceUpdateResult["target"] } { const invoice = isRecord(value) && isRecord(value.invoice) ? value.invoice : undefined; if (!invoice) throw new ResponseParseError(pathFor(id)); const current: Record<string, unknown> = {}; for (const [key, item] of Object.entries(invoice)) { if (COPY.has(key)) { if (key === "lines") current[key] = Array.isArray(item) ? item.map(copyLine) : (() => { throw new ResponseParseError(pathFor(id)); })(); else if (item !== null && !(item === "" && EMPTY_AS_UNSET.has(key))) current[key] = item; } else if (!DROP.has(key)) throw new InvoiceUpdateGuardError(`unmapped_response_key:${key}`); } if (invoice.id !== id) throw new InvoiceUpdateGuardError("mismatch:id"); if (!validPartnerId(invoice.company_id)) throw new ResponseParseError(pathFor(id)); if (invoice.company_id !== companyId) throw new InvoiceUpdateGuardError("mismatch:company_id"); if (typeof invoice.invoice_number !== "string" || typeof invoice.total_amount !== "number" || !["canceled", "uncanceled"].includes(invoice.cancel_status as string) || !["registered", "unregistered"].includes(invoice.deal_status as string) || !["sent", "unsent"].includes(invoice.sending_status as string)) throw new ResponseParseError(pathFor(id)); return { current, target: { invoice_number: invoice.invoice_number, total_amount: invoice.total_amount, cancel_status: invoice.cancel_status as string, deal_status: invoice.deal_status as string, sending_status: invoice.sending_status as string } }; }
function equal(a: unknown, b: unknown): boolean { return JSON.stringify(a) === JSON.stringify(b); }
function changes(current: unknown, next: unknown, path = ""): InvoiceUpdateResult["changes"] { if (Array.isArray(current) || Array.isArray(next)) { const a = Array.isArray(current) ? current : []; const b = Array.isArray(next) ? next : []; return Array.from({ length: Math.max(a.length, b.length) }, (_, i) => changes(a[i], b[i], `${path}[${i}]`)).flat(); } if (isRecord(current) || isRecord(next)) { const a = isRecord(current) ? current : {}; const b = isRecord(next) ? next : {}; return [...new Set([...Object.keys(a), ...Object.keys(b)])].flatMap((key) => changes(a[key], b[key], path ? `${path}.${key}` : key)); } return [{ path, current: current ?? null, next: next ?? null, same: equal(current, next) }]; }
// `.5` のように整数部を省略した形も許す（OpenAPI / create の pattern が `^-?[0-9]{0,13}(\.[0-9]{1,3})?$` で 0 桁を認めている）
function normalizedDecimal(value: unknown): string | undefined { if (typeof value !== "string") return undefined; const match = value.match(/^(-?)(\d*)(?:\.(\d+))?$/); if (!match || (match[2] === "" && match[3] === undefined)) return undefined; const integer = (match[2] === "" ? "0" : match[2]).replace(/^0+(?=\d)/, ""); const fraction = (match[3] ?? "").replace(/0+$/, ""); return `${match[1] === "-" && (integer !== "0" || fraction !== "") ? "-" : ""}${integer}${fraction === "" ? "" : `.${fraction}`}`; }
/**
 * PUT 応答の明細を、**送ったキーだけ**照合する。
 * 応答は Request に無いキー（`id` / `amount_excluding_tax` / 取引登録用の項目）を必ず返し、
 * `withholding` は required なので、両側のキーの和集合で比べると正常な応答でも不一致になる。
 * 応答に**未知のキー**が現れた場合は照合できないものとして false を返す（fail-closed）。
 */
function equalLines(expected: unknown, actual: unknown): boolean { if (!Array.isArray(expected) || !Array.isArray(actual) || expected.length !== actual.length) return false; return expected.every((value, index) => { const response = actual[index]; if (!isRecord(value) || !isRecord(response)) return false; for (const key of Object.keys(response)) if (!PUT_RESPONSE_LINE_KEYS.has(key)) return false; return Object.keys(value).every((key) => key === "unit_price" ? normalizedDecimal(value[key]) !== undefined && normalizedDecimal(value[key]) === normalizedDecimal(response[key]) : equal(value[key], response[key])); }); }
function readUpdated(value: unknown, id: number, companyId: number, plan: Record<string, unknown>, payload: Record<string, unknown>): InvoiceUpdateResult["updated"] { const invoice = isRecord(value) && isRecord(value.invoice) ? value.invoice : undefined; if (!invoice || invoice.id !== id) throw new InvoiceUpdateGuardError("mismatch:id"); if (invoice.company_id !== companyId) throw new InvoiceUpdateGuardError("mismatch:company_id"); if (typeof invoice.invoice_number !== "string" || typeof invoice.total_amount !== "number") throw new ResponseParseError(pathFor(id)); // payload には常に lines が入る（D1 の read-modify-write）。plan が触ったかで条件分けしない
  if (!equalLines(payload.lines, invoice.lines)) throw new InvoiceUpdateGuardError("mismatch:lines"); for (const key of Object.keys(plan)) if (key !== "lines" && !equal(invoice[key], payload[key])) throw new InvoiceUpdateGuardError(`mismatch:${key}`); return { id, invoice_number: invoice.invoice_number, total_amount: invoice.total_amount, webUrl: invoiceWebUrl(id) }; }
type UpdatePhase = "plan" | "readback" | "put" | "audit";
export type PayloadConstraint = { type: "string" | "integer" | "number" | "boolean" | "array"; minLength?: number; maxLength?: number; pattern?: string; minimum?: number; maximum?: number };
/** 送信 payload の OpenAPI 制約。tests/fixtures の oracle と完全一致させる。 */
export const PAYLOAD_CONSTRAINTS: Record<string, PayloadConstraint> = {
  company_id: { type: "integer", minimum: 1, maximum: 9223372036854775000 }, template_id: { type: "integer", minimum: 1, maximum: 9223372036854775000 }, invoice_number: { type: "string", maxLength: 255 }, branch_no: { type: "integer", minimum: 0, maximum: 2147483647 }, billing_date: { type: "string", pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$" }, issue_date: { type: "string", pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$" }, payment_date: { type: "string", pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$" }, payment_type: { type: "string" }, subject: { type: "string", minLength: 1, maxLength: 255 }, tax_entry_method: { type: "string" }, tax_fraction: { type: "string" }, line_amount_fraction: { type: "string" }, withholding_tax_entry_method: { type: "string" }, include_amount_brought_forward: { type: "boolean" }, amount_brought_forward: { type: "integer", minimum: -999999999999, maximum: 999999999999 }, invoice_note: { type: "string", minLength: 0, maxLength: 4000 }, memo: { type: "string", minLength: 1, maxLength: 2000 }, partner_id: { type: "integer", minimum: 1, maximum: 9223372036854775000 }, partner_code: { type: "string" }, partner_title: { type: "string" }, partner_address_zipcode: { type: "string", minLength: 1, maxLength: 10, pattern: "^[0-9]{3}-?[0-9]{4}$" }, partner_address_prefecture_code: { type: "integer", minimum: -1, maximum: 46 }, partner_address_street_name1: { type: "string", minLength: 1, maxLength: 255 }, partner_address_street_name2: { type: "string", minLength: 1, maxLength: 255 }, partner_contact_department: { type: "string", minLength: 1, maxLength: 255 }, partner_contact_email_cc: { type: "string", minLength: 1, maxLength: 255 }, partner_contact_email_to: { type: "string", minLength: 1, maxLength: 255 }, partner_contact_name: { type: "string", minLength: 1, maxLength: 255 }, partner_display_name: { type: "string", maxLength: 255 }, partner_sending_method: { type: "string" }, partner_bank_account: { type: "string", maxLength: 255 }, company_contact_name: { type: "string", maxLength: 255 }, company_name: { type: "string", maxLength: 255 }, company_description: { type: "string", maxLength: 255 }, bank_account_to_transfer: { type: "string", maxLength: 255 }, lines: { type: "array" },
};
/** 送信 payload の enum。**仕様（OpenAPI）が管理元**で、tests/fixtures/iv-invoice-show-keys.json と完全一致することをテストで固定する。 */
export const PAYLOAD_ENUMS: Record<string, readonly (string | number)[]> = {
  tax_entry_method: ["in", "out"],
  tax_fraction: ["omit", "round_up", "round"],
  line_amount_fraction: ["omit", "round_up", "round"],
  withholding_tax_entry_method: ["in", "out"],
  partner_title: ["御中", "様", "(空白)", "（空白）"],
  payment_type: ["transfer", "direct_debit", "card"],
  "lines.type": ["item", "text"],
  "lines.tax_rate": [0, 8, 10],
};
const inEnum = (key: string, value: unknown): boolean => PAYLOAD_ENUMS[key]!.includes(value as string | number);
function matchesConstraint(value: unknown, constraint: PayloadConstraint): boolean { if (constraint.type === "string") { return typeof value === "string" && (constraint.minLength === undefined || value.length >= constraint.minLength) && (constraint.maxLength === undefined || value.length <= constraint.maxLength) && (constraint.pattern === undefined || new RegExp(constraint.pattern).test(value)); } if (constraint.type === "integer") return typeof value === "number" && Number.isSafeInteger(value) && (constraint.minimum === undefined || value >= constraint.minimum) && (constraint.maximum === undefined || value <= constraint.maximum); if (constraint.type === "number") return typeof value === "number" && Number.isFinite(value) && (constraint.minimum === undefined || value >= constraint.minimum) && (constraint.maximum === undefined || value <= constraint.maximum); if (constraint.type === "boolean") return typeof value === "boolean"; return Array.isArray(value); }
function assertPayload(payload: Record<string, unknown>, id: number): void { const invalid = (): never => { throw new ResponseParseError(pathFor(id)); }; for (const key of Object.keys(payload)) { if (!PAYLOAD_TOP_KEYS.has(key)) invalid(); const constraint = PAYLOAD_CONSTRAINTS[key]; if (!constraint || !matchesConstraint(payload[key], constraint)) invalid(); } if (!("company_id" in payload) || !("billing_date" in payload) || !("tax_entry_method" in payload) || !("tax_fraction" in payload) || !("withholding_tax_entry_method" in payload) || !("partner_title" in payload) || !("lines" in payload)) invalid(); const lines = payload.lines as unknown[]; if (!Array.isArray(lines)) invalid(); if (!inEnum("tax_entry_method", payload.tax_entry_method) || !inEnum("tax_fraction", payload.tax_fraction) || (payload.line_amount_fraction !== undefined && !inEnum("line_amount_fraction", payload.line_amount_fraction)) || !inEnum("withholding_tax_entry_method", payload.withholding_tax_entry_method) || (payload.payment_type !== undefined && !inEnum("payment_type", payload.payment_type)) || !inEnum("partner_title", payload.partner_title) || lines.length === 0) invalid(); for (const [index, rawLine] of lines.entries()) { if (!isRecord(rawLine)) invalid(); const line = rawLine as Record<string, unknown>; for (const key of Object.keys(line)) if (!PAYLOAD_LINE_KEYS.has(key)) invalid(); if (!inEnum("lines.type", line.type)) invalid(); try { parseInvoicePlanLine(line, index); } catch { invalid(); } } }
function redactUpdatePayload(value: unknown): unknown { if (Array.isArray(value)) return value.map(redactUpdatePayload); if (isRecord(value)) return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, UPDATE_AUDIT_REDACT_KEYS.has(key) ? "[REDACTED]" : redactUpdatePayload(item)])); return redact(value); }
async function appendAudit(deps: InvoiceUpdateDeps, entry: InvoiceUpdateAuditEntry): Promise<void> { try { await deps.appendAudit(entry); } catch (error) { throw new AuditWriteError(error instanceof Error ? error.message : String(error)); } }
function reason(error: unknown, phase: UpdatePhase): string { if (error instanceof InvoiceUpdateGuardError) return error.reason; if (error instanceof AuditWriteError) return "audit_write_failed"; if (error instanceof ResponseParseError) return `invalid_response:${error.path}`; if (error instanceof FreeeApiError) return phase === "readback" ? `readback_http:${error.status}` : `put_http:${error.status}`; if (phase === "plan") return error instanceof SyntaxError || (error instanceof Error && error.message.startsWith("invoice plan:")) ? "plan_invalid" : "plan_read_failed"; return phase === "readback" ? "readback_network" : "put_network"; }
function isUnverified(state: InvoiceUpdatePutState): state is "unknown" | "succeeded" { return state === "unknown" || state === "succeeded"; }
export async function runInvoicesUpdate(opts: InvoiceUpdateOptions, deps: InvoiceUpdateDeps): Promise<InvoiceUpdateResult> { validateInvoiceMutationId(opts.id); const mode = opts.execute ? "execute" as const : "dry-run" as const; const base = { task_id: opts.taskId, event: "invoice_update" as const, mode, company_id: opts.companyId, invoice_id: opts.id }; let putState: InvoiceUpdatePutState = "not_attempted"; let payload: Record<string, unknown> = {}; let phase: UpdatePhase = "plan";
  try { if (opts.execute && opts.expectInvoiceNumber === undefined) throw new InvoiceUpdateGuardError("mismatch:invoice_number"); const raw = JSON.parse(await deps.readFile(opts.planPath)); const plan = parseInvoiceUpdatePlan(raw); phase = "readback"; const client = await deps.getClient(); const { current, target } = readCurrent(await json(await client.get(pathFor(opts.id), { query: { company_id: opts.companyId } }), pathFor(opts.id)), opts.id, opts.companyId); if (opts.expectInvoiceNumber !== undefined && target.invoice_number !== opts.expectInvoiceNumber) throw new InvoiceUpdateGuardError("mismatch:invoice_number"); if (target.cancel_status === "canceled") throw new InvoiceUpdateGuardError("canceled"); if (opts.execute && target.deal_status === "registered" && !opts.allowDealRegistered) throw new InvoiceUpdateGuardError("deal_registered"); payload = { ...current, ...plan, company_id: opts.companyId }; if (payload.partner_title === "（空白）") payload.partner_title = "(空白)"; if (plan.partner_code !== undefined) delete payload.partner_id; else if (plan.partner_id !== undefined || validPartnerId(payload.partner_id)) delete payload.partner_code; else delete payload.partner_id; if (validPartnerId(payload.partner_id) === validPartnerCode(payload.partner_code)) throw new ResponseParseError(pathFor(opts.id)); assertPayload(payload, opts.id); const result = { mode, companyId: opts.companyId, id: opts.id, target, unobservable: UNOBSERVABLE, changes: changes(current, payload), totals: computeInvoiceTotals(payload as never), payload }; if (!opts.execute) { phase = "audit"; await appendAudit(deps, { ...base, timestamp: deps.now().toISOString(), status: "planned", payload_redacted: redactUpdatePayload(payload), put_state: putState }); return result; } let response: Response; try { phase = "put"; putState = "unknown"; response = await client.put(pathFor(opts.id), { body: payload, redirect: "manual" }); putState = "succeeded"; } catch (error) { putState = classifyInvoicePutState(error); throw error; } const updated = readUpdated(await json(response, pathFor(opts.id)), opts.id, opts.companyId, plan, payload); phase = "audit"; await appendAudit(deps, { ...base, timestamp: deps.now().toISOString(), status: "updated", payload_redacted: redactUpdatePayload(payload), put_state: putState }); return { ...result, updated };
  } catch (error) { const failure = reason(error, phase); let auditFailure = error instanceof AuditWriteError; if (!auditFailure) { try { await appendAudit(deps, { ...base, timestamp: deps.now().toISOString(), status: "failed", payload_redacted: redactUpdatePayload(payload), reason: failure, put_state: putState }); } catch (auditError) { auditFailure = true; if (!isUnverified(putState)) throw auditError; } } if (isUnverified(putState)) throw new InvoiceUpdateUnverifiedError(auditFailure ? "audit_write_failed" : failure, putState); throw error; }
}
export function formatInvoiceUpdate(result: InvoiceUpdateResult): string { const actionable = result.changes.filter((change) => !change.same); return [`mode: ${result.mode}`, `target: invoice_number=${result.target.invoice_number} total_amount=${result.target.total_amount}`, `参考値（確定値は freee の応答を正とする）: 小計 ${result.totals.subtotal} / 消費税 ${result.totals.tax} / 合計 ${result.totals.total}`, `changes: ${actionable.length}`, ...actionable.map((change) => `${change.path}: ${JSON.stringify(change.current)} -> ${JSON.stringify(change.next)}`), ...(result.target.sending_status === "sent" ? ["warning: 送付済みの請求書を更新します"] : []), result.updated ? `updated: id=${result.updated.id} invoice_number=${result.updated.invoice_number} total_amount=${result.updated.total_amount}\nweb: ${result.updated.webUrl}` : "実 PUT は行っていません（--execute で更新）", "payload:", JSON.stringify(result.payload, null, 2)].join("\n"); }
